### ISSUE TITLE
Wollok works badly (unusable) under ubuntu 16.04 (64 bits)

### ISSUE THREAD

**Issue by lgassman** [uqbar-project/wollok#940] opened 2016-08-24 16:26 UTC
Wollok works badly under ubuntu 16.04.

The Wollok IDE starts succesfuly, but when a Wollok project is created, the wizard never ends. After Wollok is restarted, the project is created, but it isn't able to execute it by REPL. It never finished initializing.

I tested it using oracle JDK 1.8.101 and 1.8.102 and Openjdk-8. 
I checked using jconsole which VM was used in each execution.

I tested it using 3 different  PC with similar characteristic. (I attach Hardware info), but another students reported to me the same issue on their personal computers, using Ubuntu 16.04.

Wollok was able to execute correctly under windows 7 OS in the same computers.

I checked the eclipse log. I found exceptions, but I am not sure if they are relevant.

I attach 2 screenshots of Wollok: It is creating a project and it is executing a wlk file by REPL .

Additional Info:
 **output of OS console.**
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=64M; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
log4j:WARN No appenders could be found for logger (org.eclipse.xtext.ui.internal.Activator).
log4j:WARN Please initialize the log4j system properly.

**last jdk version used**
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**uname -a output** 
Linux infor38B00 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Eclipse Log**
[eclipse.log.txt](https://github.com/uqbar-project/wollok/files/435168/eclipse.log.txt)

**lshw output**
[lshw.log.txt](https://github.com/uqbar-project/wollok/files/435159/lshw.log.txt)

![ejecutando](https://cloud.githubusercontent.com/assets/3935208/17938697/7cfff23c-69fd-11e6-9d0f-d107a650984f.png)
![creandounproyecto](https://cloud.githubusercontent.com/assets/3935208/17938695/7cfa6b50-69fd-11e6-8f7a-951b88666ed3.png)
![infoubuntu](https://cloud.githubusercontent.com/assets/3935208/17938696/7cfe035a-69fd-11e6-9d4f-bd0a29723072.png)

**Comment by Juancete** [comment] 2016-08-24 21:29
Have you tried another Eclipse without wollok? I found the same issue and is caused by GTK3. 

Take a look at [this post](https://bugs.launchpad.net/ubuntu/+source/java-common/+bug/1552764)

You can fix it by adding the following line at wollok.ini
```
--launcher.GTK_version
2
```

**Comment by lgassman** [comment] 2016-08-25 14:47
A student tested it and works, but it's important the order of lines. I
copy the response of student. I would recommend to write it into wollok
installation page.

"Hola! si funciona pero no es simplemente agregar esas lineas, hay que
agregarlas por el medio. Aviso importante:

Solo funciona si abren desde el ejecutable wollok y no ellauncher

el contenido final del wollok.ini es este:

-startup
plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417
--launcher.GTK_version
2
-vmargs
-XX:PermSize=64M
-XX:MaxPermSize=128M"

**Comment by Juancete** [comment] 2016-10-06 01:03
This is on the wollok installation page

http://www.wollok.org/instalacion/#error-al-crear-un-proyecto-wollok-en-ubuntu

Can we close it?

**Closed** 2016-10-06 01:05 UTC
Labels: bug, complexity: 4 - Hard, product, severity: 4 - Show Stopper
