### ISSUE TITLE
In the REPL strings are shown without quotation marks

### ISSUE THREAD

**Issue by gcrespi** [uqbar-project/wollok#875] opened 2016-08-01 13:03 UTC

**Comment by fdodino** [comment] 2016-08-21 14:08
@npasserini @javierfernandes @tesonep Is it ok to add quotation marks in REPL responses? 
@flbulgarelli  @gcrespi ,  Why was this issue reported with a Medium severity label? What are the consequences for students?

**Comment by flbulgarelli** [comment] 2016-08-21 19:47
@fdodino  the problem is that it introduces ambiguities that may not be so terrible within the context of the REPL, but that difficult debugging and understanding what is going on in more complex situations.

_Side note: I think that the actual problem is not with the REPL itself, but the `toString` method._

For example, the following three consults produce the same `toString`: 

```wollok
[pepita]
>>> [true]
[true]ruby
>>> ["true"]
[true]
>>> "[true]"
[true]
```

Which means that in a lot of cases the toString will lead into messages that are impossible to understand to a newcomer: 

```wollok
>>> assert.equals([true], "[true]")
wollok.lang.Exception: Expected [[true]] but found [[true]]
``` 

Compare it to ruby's to_s/ haskell's show: 

```ruby
[9] pry(main)> [true]
=> [true]
[10] pry(main)> "[true]"
=> "[true]"
[11] pry(main)> ["true"]
=> ["true"]
```

```haskell
Prelude> [True]
[True]
Prelude> ["True"]
["True"]
Prelude> "[True]"
"[True]"
Prelude> 
```

**Comment by fdodino** [comment] 2016-08-22 02:08
@flbulgarelli I don't know if a situation like 
>>> assert.equals([true], "[true]")
could arise in an initial course.
My brain says "Ok, let's do it and see if tests pass ok"
But my intuition says "Wait this year and see if the absence of quotation marks have consequences for students".
Maybe I need to hear another opinions, @matifreyre @lgassman @asanzo (I can't find Lucas)

**Comment by flbulgarelli** [comment] 2016-08-22 02:38
@fdodino actually they were my students who noticed that inconsistency during the first class, while using the repl and noticing that `"1"` and `1` produced the same result :stuck_out_tongue:

**Comment by asanzo** [comment] 2016-08-22 03:34
Hi! 

What are the implications of having:

```xtend
"hola".toString() == "\"hola\""
```

instead of:

```xtend
"hola".toString() == "hola"
```

? 

Today I like Franco's reasoning, but I agree with Fer that it is not a major problem. 

@fdodino, Do you see an additional reason why we should stay like we are?

Just thinking: Do we expect this to happen?

```xtend
x.toString() == x.toString().toString()
```

I don't know. Right now I'd say as Homer: I like my beer cold, my tv loud, and my strings with quotation marks.

Lucas is @lspigariol

**Comment by npasserini** [comment] 2016-08-22 12:21
Short story:
I agree that strings should be shown with "" in REPL.
But I am strongly against changing toString method at this stage, it
requires a LOT more thinking.
So, if you want a fast change, change the REPL, not the objects themselves.

Practical/empirical longer story:
toString message migth be sent in many places, probably the toString of
lots of objects depends so if you change it you will be putting " in lots
of toStrings in undesired places, it will just not work. Or at least it is
very dangerous. I am not sure that tests will cover it, it could introduce
bugs, and we have an already started semester.

More philosophically, I already proposed that we need two (or even three)
flavors of "toString" with different names:
- I think that *toString* has to be kept for more technical issues,
internal debugging, should be very simple, guaranteed not to fail because
it will be used by debugging and other internal tools.
- *printString* provides a visual representation, for showing to the
user... yes, an object could have many of these, but it is nice that we
have at least one.
- *asString*, converts an object to a String, and is just another member of
many asXXX methods.

Names could change, I do not care.

Also we could (or should!) discuss these categories. But I think that at
least we should have two different "toString", and one of them should be
the identity function on strings, because otherwise we loose polymorphism
with the rest of the objects.

I would not change toString... at least I would not until we discuss this
and we analyze the impact for each core object... and maybe after that I
think that we could probably let toString as is and add another method for
the new version.

So a fast way to add it would be to do it in the REPL.
Or a nicer way could be to add printString, implement it as you proposed
for toString and review which toStrings have to be changed for printString.

**Comment by tesonep** [comment] 2016-08-22 12:24
+1 Nico, changing the Repl is the answer.

**Comment by javierfernandes** [comment] 2016-08-22 13:15
I also would like to change the REPL and not the core objects.
But I'm afraid that's not completely possible.
That could work for simple objects/strings, but for lists for examples, the
REPL will be calling "toString()" on the list and the logic to translate
each object into strings is within Collection class, so the REPL won't be
able to intercept that and show something like [ "a", "b ] instead of [ a,
b ].

Unless the REPL starts to send another message like "print"

**Comment by fdodino** [comment] 2016-08-22 16:52
Ok, agree with Nico that changing toString() implementation for Strings scares me a lot.
But if we just add a printString() method in Object that simply does self.toString(), overriden by String as toString() plus quotation marks, and if Repl console just asks for printString() method instead of toString(), that would do. Still if you do something like
assert.equals([true], "[true]")
you would get the error message 
wollok.lang.Exception: Expected [[true]] but found [[true]].
But I really don't think this is a good use of the language.

**Comment by flbulgarelli** [comment] 2016-08-22 17:25
:+1: to adding a `printString`.

**Comment by lspigariol** [comment] 2016-08-22 17:29
i like show "" in Repl and error messages too.
agree with diferentiate print/show from convert/cast semantic

(i cant explain argumentations in issues comment nasty oficial language)

**Comment by flbulgarelli** [comment] 2016-08-22 17:40
@lspigariol si se te complica comená en español che :stuck_out_tongue:

**Comment by fdodino** [comment] 2016-08-22 19:50
Well, thanks to Javi I've fixed in my branch the behavior of REPL console

```scala
>>> var saludo = "hola"
"hola"
>>> saludo == "hola"
true
```

And also fixed weird __synthetic0  and REPL lines of stack  trace:

```scala
>>> "hola".concat(3)
wollok.lang.MessageNotUnderstoodException: hola does not understand concat(p0)
	at wollok.lang.Object.messageNotUnderstood(name,parameters) [/lang.wlk:212]
```

But now printString is unnecesary, I think:

```scala
>>> saludo.printString()
""hola""
```

I'd rather delete printString implementation.

**Comment by npasserini** [comment] 2016-08-23 08:08
Why not call printString in the error message?

**Comment by fdodino** [comment] 2016-08-23 16:47
Added printString for assert expectations

**Comment by fdodino** [comment] 2016-08-31 11:07
Merged in REPL-fixes branch

**Closed by fdodino** 2016-08-31 11:07 UTC
Labels: severity: 2 - Medium
