### ISSUE TITLE
Single constructor

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#559] opened 2015-12-30 23:13 UTC
# The problem

Currently, Wollok support multiple constructors. This has the advantage of being able to declare multiple ways of _configuring_ an object in a compact manner. It doesn't force you to delegate to a main constructor, neither.

However, this also has many drawbacks:
- It makes the model more complex: there are not only multiple ways of _configuring_ an object - which is good, since with it you can build flexible domain models - but also multiple ways of _instantiating_ the object
- If you want an instance of an object, it is not clear which constructor you have to pick
- It allows you to create constructors that don't set initial values for internal collaborators, which is a bug source
- It sometimes create the idea of "default values" which is very tricky: unless you look into the docs, it is not obvious which are the default values
- You cannot reveal the intention of the constructor by assigning a good expressive name to it - they all are 'new'. 
- It makes you easily enter into the telescopic constructor (anti)pattern, which is very rigid: if you have three construction parameters A, B, C and you want to be able to have a constructor with optional dependencies, you end up creating the combinatory of all the posibilities 
- It embeds the creational part into the domain part, since object not only knows how to behave , but also understand how to be configured. 
  - It does not make the essential dependencies obvious
  - You need to add the concept of constructor delegation, that is more a language thing than an OOP concept. And its current syntax is not clear at all. 
- Wollok is a dynamic typed language, so you cannot use argument types to choose the proper constructor, just their count. This restricts even more the expressiveness of multiple constructors  
# Some examples:
## Loss of intention reveling

_I took this example for the wollok sdk_

Lets assume you have a point constructor with two arguments - which is quite obvious that are x and y because that is the way points are described in the flat space - But then you have an extra, no args constructor: `Point.new()`. Which are the default values? Which states does it have? Was it created in the origin (0,0), in (1, 1), in (-1, -1) or in (nil, nil). I think it is not obvious, because there is no notion of default value in mathematical points. 

But, we could instead have a class method, or a companion object method - I wan't to discuss it here, it should be another issue - called `origin`, that is more clear: `Point.origin()` or `Point.empty()` or    `Point.unitary()`
## Telescopic constructors

When things get more complex, you end up in a telescopic constructor antipattern. But you can and should usually refactor it to a builder. Although I can not cite a good paper about it, there are dozens of posts about that problem: 
- http://www.captaindebug.com/2011/05/telescoping-constructor-antipattern.html#.VoRg3N8zrVM
- http://stackoverflow.com/questions/5603108/refactor-to-use-builder-pattern-or-telescoping-constructor-pattern
- https://kodelog.wordpress.com/tag/telescopic-constructor-pattern/
- http://khsjava.blogspot.com.ar/2010/11/replace-telescoping-constructor-with.html
- https://en.wikipedia.org/wiki/Builder_pattern
- http://www.kgolev.com/when-your-fat-model-is-too-fat/
- http://tonyarnold.com/2014/12/13/death-to-telescoping-constructors.html
# My proposal

My proposal is to simply remove multiple constructors. JS and Ruby do that, showing that it is possible.

**Comment by javierfernandes** [comment] 2015-12-31 01:52
I would need concrete examples.
What you want to do can be done already. Just use a single constructor, and then use a factory object (like a companion object).
Wollok currently doesn't let you (need to analyse it better) have a companion object with the exact same name as the class but you can do

```xtend
class Point {
    new(x,y) { ... }
}

object Points {
    method origin() = new Point(0,0)
    ....  // whatever 
}
```

> It embeds the creational part into the domain part, since object not only knows how to behave , but also understand how to be configured.

The **object** doesn't now how to be configured, but the class. Constructors are part of the class and not of the object.

I don't see how the first cited link example would be different from the same issue you will have using method overloading (which is the case with factory methods).

I'm afraid that, unless we provide some sort of **new unseen mechanism at language support** we are just moving the problem from constructors to methods but it will be the same.
It could be something like:
* specifying required instance variables in the class itself
* then having a language mechanism to build and set all instance variables, with static checks (not just an untyped map like all the dynamic languages) which will check var names as well as required vars being set.

```
class Point {
    mandatory var x
    mandatory var y
    var board
}

new Point(x = 10, y = 10)
new Point(x = other.x(), y = other.y(), board = myBoard)

new Point(board = myBoard)   // wont compile! you must set x and y !
```

A couple of other comments

> It makes the model more complex: there are not only multiple ways of configuring an object - which is good, since with it you can build flexible domain models - but also multiple ways of instantiating the object

Yes, same as having factory methods

> If you want an instance of an object, it is not clear which constructor you have to pick
Yes, same as with any overloaded method.

> It allows you to create constructors that don't set initial values for internal collaborators, which is a bug source.

This is true. It currently checks it partially if the instance variables are immutable (vals). But it is true that it is not always the case.
As I said the other option is to specify this concern in the variable itself expressing the idea that, that variable must always be present.
Actually this seems like the **invariant** concept of **design by contract** which is a feature we would also want to try out.

Think that even if you have a single constructor that "express" this constraint, you are still not making sure that the variable has always a value. Which will apply if it is modelled as an invariant. The variable will be checked in all methods of the class.

> It sometimes create the idea of "default values" which is very tricky: unless you look into the docs, it is not obvious which are the default values

I don't seem the difference from method overloading

> You cannot reveal the intention of the constructor by assigning a good expressive name to it - they all are 'new'.

Again, currently can be done with factory methods.
Another option would be naming constructors

```xtend
class Point {
   constructor(x, y) { ... }
   constructor origin() = this(0, 0) 
}
```

But then this changes the syntax to:
```xtend
val p = Point.new(0, 0)
val p2 = Point.origin()
```

Which is the same syntax as any message send.
I'm not sure the effects of this, and collisions.

> You need to add the concept of constructor delegation, that is more a language thing than an OOP concept. And its current syntax is not clear at all.

Yes, it s a different thing than method delegation. So the syntax is different because of that. I didn't wanted to confuse the fact that it is a special concept.
I found the current syntax more declarative than the one Java has, in which you need to write the delegation as part of the body, but... it is special because it is the first thing you must do.
So for me it is even weirder to have it as part of the body.
I haven't found any better syntax in other languages that have the same constructor delegation mechanism.
As with any thing that is different from another language you need to understand it and learn to use it.

> Wollok is a dynamic typed language, so you cannot use argument types to choose the proper constructor, just their count. This restricts even more the expressiveness of multiple constructors

Remember that although Wollok still doesn't have a type system we will have it, and that could address the issue of expressiveness on constructor usage and maybe allowing to have constructors with the same arity but different types. You just won't explicitly write them.

**Comment by javierfernandes** [comment] 2015-12-31 02:25
Maybe this can be addresses as a wollok "flavor".
We really need a way to model language features and disable things at
parsing level

**Comment by flbulgarelli** [comment] 2015-12-31 02:49
Hey, wait.... named constructors, that is reaaaaly interesting!

I think it solves many of the problems I addressed. 

I also liked the idea of tagging parameters on the constructor, as you pointed out, but named constructors seem to be something that is both simple AND powerful. 

What about the following semantics?

  * Classes have a 0 or 1 constructors
  * If they have more than one, the non default constructors must be named

**Comment by npasserini** [comment] 2015-12-31 04:53
On Wed, Dec 30, 2015 at 10:52 PM, javierfernandes <notifications@github.com>
wrote:

> class Point {
>    constructor(x, y) { ... }
>    constructor origin() = this(0, 0)
> }
>
> The named constructor idea sounds interesting.

> But then this changes the syntax to:
>
> val p = Point.new(0, 0)val p2 = Point.origin()
>
> Which is the same syntax as any message send.
> I'm not sure the effects of this, and collisions.
>
Yup, that could be a problem.

> You need to add the concept of constructor delegation, that is more a
> language thing than an OOP concept. And its current syntax is not clear at
> all.
>
> Yes, it s a different thing than method delegation. So the syntax is
> different because of that. I didn't wanted to confuse the fact that it is a
> special concept.
> I found the current syntax more declarative than the one Java has, in
> which you need to write the delegation as part of the body, but... it is
> special because it is the first thing you must do.
> So for me it is even weirder to have it as part of the body.
> I haven't found any better syntax in other languages that have the same
> constructor delegation mechanism.
> As with any thing that is different from another language you need to
> understand it and learn to use it.
>
I am not sure about making constructor delegation so special.
I am even less sure about forcing super() (or this()) to be the first
action in a constructor.

> Wollok is a dynamic typed language, so you cannot use argument types to
> choose the proper constructor, just their count. This restricts even more
> the expressiveness of multiple constructors
>
> Remember that although Wollok still doesn't have a type system we will
> have it, and that could address the issue of expressiveness on constructor
> usage and maybe allowing to have constructors with the same arity but
> different types. You just won't explicitly write them.
>
I am full of insecurity... but I am not sure that it could be possible to
typecheck that.

>

**Comment by npasserini** [comment] 2015-12-31 05:10
While named constructors look nice, I think we should give a try to the
"class parameters" idea.
The scala way solves many of our problems

class Point(var x, var y, var board)

Bad: The main problem for which I to not have a nice solution is that
now we have two ways of defining fields... which is a very confusing
thing of Scala.

Good: Besides solving the problems already described before, this
solution avoids us the boilerplate of copying constructor parameters
to fields.

The idea is that any class parameter without a default value is
mandatory to be received on construction time.
If you want that the default value of a field to be null, you could
assign it to null explicitly.

Doubt: I am thinking that you do not want to expose all fields to the
user, therefore I would declare explicitly those that can be set from
outside.

Alternative 1: use a keyword to mark the fields that can be set at
construction time.
Bad: I can not think about a good keyword for that.

class Point {
    seteamela var x
    seteamela var y
    seteamela var board = null
}

Would be equivalent to Javi's

class Point {
    mandatory var x
    mandatory var y
    var board
}

Maybe we could use mandatory and optional, I don't know.

Alternative 2: Alternative 1 requires to use named constructor parameters,
the first idea could work with named parameters as well as with positional
parameters... we could even allow for both of them.
The bag thing here is that named parameters someway reproduce the
boilerplate of the current constructors:

class Point {

   val x, y

   constructor(_x, _y) { x = _x ; y = _y }
}

val p = new Point(0,0)

would change to

class Point {

   mandatory val x

   mandatory val y

}

val p = new Point(x = 0, y = 0)


To tomplete this no-constructor solutions, we could add an initialize
method which is called after construction.

**Comment by flbulgarelli** [comment] 2015-12-31 05:27
I love the Scala way, but I agree with you that it introduces two different ways of declaring collaborators. It is complex for newcomers.

If you don't like named constructors nor single constructor + class methods/companions, I think that both named parameters (1) or positional parameters (2) for mandatory fields could work. 

But, I think it is not necessary to add a mandatory/optional flag: if your collaborator is initialized, then it is optional (1) or not part of the constructor (2). Otherwise, it is mandatory.

That has a simple an clear semantics: you must explicitly fulfill all dependencies - either with an initializer or by constructor. 

E.g.:


```
class Point {
    var x
    var y
    var board = null
}
```

`Point.new(0, 0) // Alternative (1)`

`Point.new(x = 0, y = 0) // Alternative (2)`
`Point.new(y = 0, x = 0) // Alternative (2)`
`Point.new(x = 0, board = aBoard, y = 0) // Alternative (2)`

**Comment by javierfernandes** [comment] 2015-12-31 16:26
Just a note, I think that named constructors can be implemented without changing the "new" syntax.
Just that they will be used for expressiveness on its declaration and not its usage.
Example:
```xtend
class Point {
    constructor(x, y) ...
    constructor origin() = this(0, 0)
    constructor withOtherPoint(point) = this(point.x(), point.y())
}
```
Then used
```xtend
   val p = new Point(10,10)
   val p2 = new Point()   // uses origin, and navigates to that one (linker)
   val p3 = new Point(other)  // linked to "withOtherPoint"
```

**Comment by flbulgarelli** [comment] 2015-12-31 16:59
But... the most problematic loss of expressiveness is in its usage, not its declaration...

**Comment by flbulgarelli** [comment] 2016-01-01 17:15
@fedescarpa @faloi @mfreyre @asanzo @gprieto

**Comment by npasserini** [comment] 2016-01-01 23:24
On Thu, Dec 31, 2015 at 2:27 AM, Franco Leonardo Bulgarelli <
notifications@github.com> wrote:

> I love the Scala way, but I agree with you that it introduces two
> different ways of declaring collaborators. It is complex for newcomers.
>
> If you don't like named constructors nor single constructor + class
> methods/companions, I think that both named parameters (1) or positional
> parameters (2) for mandatory fields could work.
>
I personally like companion objects, but. While teaching Scala, I've also
seen that companion objects confuse students (even advanced ones).
One curious thing is that you end up with
object Foo { /* here you put 'class' methods */ }
class Foo { /* here you put 'instance' methods */ }

So the syntax becomes confusing.

Anyway, you can write named object now in Wollok... I am not sure if there
is a restriction from naming it the same of an existing class... we could
remove that description.
Maybe we could teach them not as "class methods" but just as a "good
practice" or "pattern" (which is also true for Scala, there is no
relationship between classes and their "companion" objects.
Maybe the confusion in Scala comes from the use of the term "class method"
(which Scala does not truly implement) and maybe also because of having
students that have previous knowledge of class methods (which might not be
a problem for wollok students).


So... you always could have your

Point.origin()

just that:
(a) you would not be enabled to implement it inside the point class...
which I am not sure if it is good of bad.
(c) I comes up to how you want to explain those concepts.

> But, I think it is not necessary to add a mandatory/optional flag: if your
> collaborator is initialized, then it is optional (1) or not part of the
> constructor (2). Otherwise, it is mandatory.
>
> That has a simple an clear semantics: you must explicitly fulfill all
> dependencies - either with an initializer or by constructor.
>
> E.g.:
>
> class Point {
>     var x
>     var y
>     var board = null
> }
>
> Point.new(0, 0) // Alternative (1)
>
> Point.new(x = 0, y = 0) // Alternative (2)
> Point.new(y = 0, x = 0) // Alternative (2)
> Point.new(x = 0, board = aBoard, y = 0) // Alternative (2)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uqbar-project/wollok/issues/559#issuecomment-168127469>
> .
>
Yes, this sound correct.
I was wandering if it is clear enough that any uninitialized field has to
be included in the constructor call.

Also this would be a brand new solution, different from any language I
know.... we should take those kind of steps very carefully.

**Comment by flbulgarelli** [comment] 2016-01-01 23:36
Yes, @npasserini you are right about that it is a brand new solution in object oriented languages - but It resembles the struct/data initialization in C or Haskell -. I am not personally too inclined to reinvent the wheel, but in this case I vote for trying it. Because

* It is simple: no more having to declare constructors. No telescopic constructors. No self delegation. No super constructor delegation. 
* It (seems) easy to understand too: you need to initialize everything in the instantiation, unless you have provided a default value
* It is flexible
* It is robust: the language should enforce that you provided everything

**Comment by npasserini** [comment] 2016-01-01 23:47
Ok, only one more detail, I think you cannot totally avoid super
constructor delegation.
See this example (current syntax)

class A {
  var x, y
  constructor(_x, _y) { x = _x; y = _y }
}

class B inherits A {
  constructor(x) = super(x, 0)  // fixes parent attribute
}

or even

object C inherits B(0) // we have an example of this on Keys objects.


In the proposed syntax this could become:

class A { var x, y }
class B extends A(y=0)
object C extends B(x=0)


One more problem with this idea is that you could change from out side ANY
internal collaborator, while the current constructor syntax gives the class
more control about it.

**Comment by matifreyre** [comment] 2016-01-04 14:06
I'm sorry, but I feel I´m missing something...

Am I wrong if I say this proposed change would only work for cases when you don't want any kind of logic within the constructor but for variables' assignments? What if you want to send a message to the argument instead of just assigning it to a variable? Are you thinking that that should forcibly be a different message name in the WKO/companion (which in terms would use the real constructor)?

**Comment by matifreyre** [comment] 2016-01-04 14:13
I'm sorry, I missed this phrase before: 
"To complete this no-constructor solutions, we could add an initialize method which is called after construction."
Please ignore my previous comment.

**Comment by npasserini** [comment] 2016-01-04 14:47
Still, it is a real situation that the no-constructor solution is less
powerful than the current one, there are some cases that are not covered.
But one could argument that those cases are rare in most typical pdep
programs and that it is not justified to complicate the language to serve
those rare cases.

To deal with any situation, the solution under discussion gives several
posibilities with increasing degrees of power and complexity:
1) Only variable initialization, no constructor is needed, validations are
provided to guarantee that any field is initialized. I think this is the
most common case and which we would be prioritizing.
1.1) Slightly more complex, you could initialize a field to nil/null, you
have to do it explicitly because otherwise the checker will force you to
provide a value.

2) As you said in the last mail, include an "initialize" message, which
allows for sending messages to the initialized objects.
This should be called automatically after the variable initialization.
Since it is a simple message and not a special constructor, there are less
concepts to explain and inheritance works as always.

3) More advanced, if you require different kinds of initialization, you
move the creation to a "factory method", so you could provide for named
"object creators".
I think it is preferable to talk about factory method than class methods,
as they require less from the language and provide more usage possibilities.
A common pattern could be to place factory methods on an object with the
same name of the class, you could include the name "companion object" or
not.
But nothing prevents you to place factory methods anywhere else, when the
designs calls for it.

3.1) Also, factory methods could send further messages to an object, after
#initialize.

I think that this should allow for all the flexibility we need for pdep (or
similar subjects).

**Comment by matifreyre** [comment] 2016-01-04 14:56
I couldn't agree more.

**Comment by fdodino** [comment] 2017-11-06 14:31
@npasserini , shouldn't we close this issue?

**Comment by npasserini** [comment] 2017-11-06 23:03
Ok

**Closed by npasserini** 2017-11-06 23:03 UTC
Labels: type: Question / Discussion
