### ISSUE TITLE
[REPL] Confusing synthetic stack frames in the REPL grow on each new line executed

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#764] opened 2016-06-23 14:53 UTC
See the following repl session: 

```
>>> [m4 / 0
[31mwollok.lang.Exception: / by zero
	at wollok.lang.Integer./(other) [/wollok.wlk:494]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/metodos.wlk:2]
```

What does the synthetic frame mean? Why are they duplicated? Can we remove them?

**Comment by fdodino** [comment] 2016-06-30 21:00
:+1:  Could we also remove REPL frames in stack trace? @npasserini @javierfernandes

**Comment by npasserini** [comment] 2016-06-30 21:43
I have no idea what all synthetic means... does it happen always when you
evaluate that expression?

**Comment by javierfernandes** [comment] 2016-07-01 00:15
I would need to test it myself. But syntheric are parta generated by the
repl impl. It has like a template program and pastes your content in there.
Theres no file for that program. Is in memory

**Comment by npasserini** [comment] 2016-07-01 08:23
I get that, but why do we have 10 synthetic frames?

**Comment by javierfernandes** [comment] 2016-07-12 01:20
I tested this program

```xtend
program abc {
	var a = 0
	var b = 12 / a
	console.println('Hello Wollok')
}
```

and the console was

```java
[WARNING] /Users/jfernandes/dev/data/repo/wollok-dev/wollok-tests/src/bugs/testingSynthetic.wpgm:4:31 WARNING Unused variable
wollok.lang.Exception: / by zero
	at wollok.lang.Integer./(other) [/lang.wlk:1017]
	at  [/testingSynthetic.wpgm:4]
```

Pretty good.

So I think that the problem is in the REPL.

**Comment by javierfernandes** [comment] 2016-07-12 01:21
The REPL seems to be creating new stack elements (or not cleaning them in case of an exception)

Proof

```xtend
Wollok interactive console (type "quit" to quit):
>>> var a = 0
0
>>> var b = 12 /a
wollok.lang.Exception: / by zero
	at wollok.lang.Integer./(other) [/lang.wlk:1017]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/b36.wlk:1]

>>> var b = 12 / a
wollok.lang.Exception: / by zero
	at wollok.lang.Integer./(other) [/lang.wlk:1017]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/b36.wlk:1]

>>> var b = 12 / a
wollok.lang.Exception: / by zero
	at wollok.lang.Integer./(other) [/lang.wlk:1017]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/b36.wlk:1]

>>> var b = 12 / a
wollok.lang.Exception: / by zero
	at wollok.lang.Integer./(other) [/lang.wlk:1017]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/b36.wlk:1]
```

**Comment by javierfernandes** [comment] 2016-07-12 01:29
Ok.
This is basically how the REPL currently works.
Which sucks, but well.

Each line you write it reuses the same interpreter, and therefore the context.
Each new line "pushes" a new stack frame with the new content, so that all previous lines are availables as parent context.

For example this program

```xtend
var a = 2
var b = 3
var c = a + b
```

Creates a stack like this
```bash
  (a)
    `-- (b)
            `-- (c)
```

And so on.
If you have a 100 lines REPL session then you will have a 100 depth stack.

I'm not sure how to solve this easily :S

**Comment by fdodino** [comment] 2016-07-14 12:23
@javierfernandes @npasserini @tesonep 
At least, can we filter stack trace lines like "at  [/__synthetic0.wpgm:3]"?

**Comment by javierfernandes** [comment] 2016-07-14 13:06
Well, that wouldn't be correct for other regular program execution (not
REPL).

I prefer not to hack this :P

**Comment by npasserini** [comment] 2016-07-15 23:24
If I can get my eclipse back to work, I will be adding a pull request of
the server branch, which includes the possibility of customizing wollok
console.

That said, I think that you could run repl with a customized console and
put the hack there. Currently a console has a method logError(Throwable
exception) which prints it stacktrace, so you could work with the stack
trace and decide which lines to print. I.e. do not change the stack trace,
just decide what to print.

@javierfernandes, do you think that this could be acceptable?

**Comment by javierfernandes** [comment] 2016-07-16 02:00
Thats fine.

Although i still would like to think about the current design of the repl.
I'm not sure if the stack based solution is scalable or not. I don't have a
better solution yet. Still is a mid term change.

**Comment by npasserini** [comment] 2016-07-16 06:47
On Sat, Jul 16, 2016 at 4:00 AM, javierfernandes <notifications@github.com>
wrote:

> Although i still would like to think about the current design of the repl.
>

Agree, I do not like the stack either.

But, why do we need a stack based solution?
I do not know which is the problem that forced us to do so.

**Comment by javierfernandes** [comment] 2016-07-16 13:49
It is not exactly a stack. Oh well, yes we do have a Stack object and the
interpreter when called "performOnStack" pushes a new element to the stack,
executes a closure and the pops it.

Elements on the stack are EvaluationContext (interface).
They are actually connected between each other like a linked list. An
evaluation Context could have a parent. If it doesn't resolve a variable
then it goes up to the parent, and so on.

I think that it also follows the nature of function/method calls, right ?
I'm how would it be without a stack.
I guess that the EvaluationContext should be passed for all evaluating
methods of the interpreter.
Since the interface of the interpreter is to evaluate an EObject.
And the problem here is that are EObject (and mostly in xtext) are
autogenerated, therefor we cannot add them state.
Which is the main usage of the stack, to isolate state (scope) with the
EvaluationContext.
Types of EvaluationContext:

   - *WollokObject*: the "self". This is not a EObject. Although created
   from one
   - *MapBased:* used for invoking methods holding parameter values
   - *Composite: *to compose them, like when running a method you have a
   Composite of MapBased (local and parameters) + WollokObject (self). Also if
   the object was a literal, it will have a parent EvaluationContext, which
   could also be a Composite, if the object was defined in a method, with new
   locals + another self.


Also probably the stack should be in a Thread object and not in the
interpreter, for example for multithreading

Most of this design is decoupled from Wollok into a generic package called
"org.uqbar.project.xinterpreter".
I wanted to abstract away it along with the debugger infraestructure and
make it a separated open source project to contribute to XText for anyone
who wants to build an interpreter, not to start from scratch.
You can checkouthere: context, interpreter, stack & debugger.

How could this be without a stack ?
Also notice that this stack is not the same as in "stack-oriented
languages".

**Comment by matifreyre** [comment] 2016-07-16 13:50
Not sure if it's related to this, but just in case... there's a test for the stack trace that's failing in dev because of the EOL at ExceptionPropagationInNativeTestCase.nativeMethodCallsWollokClosureThrowingASimpleException

wollok.lang.Exception: Expected [wollok.lang.Exception: SoundGarden
        at  [natives.wpgm]
        at natives.Repeater.ntimes(n,closure) [natives.wpgm]
        at  [natives.wpgm]
] but found [wollok.lang.Exception: SoundGarden
        at  [natives.wpgm]
        at natives.Repeater.ntimes(n,closure) [natives.wpgm]
        at  [natives.wpgm]
]

I'm working under Windows, and when I debug the WString.equals I see this:

![image](https://cloud.githubusercontent.com/assets/10454118/16895167/d4aee8e6-4b42-11e6-9023-16a53a384e32.png)

**Comment by javierfernandes** [comment] 2016-07-16 13:57
Only on Windows, right ?
It works fine for me and travis (I believe).

Can you please try to modify the test to avoid using xtend RichStrings
(triple ''') and use a regular string ?
To see if that fixes it

**Comment by matifreyre** [comment] 2016-07-16 20:25
I only work on Windows, so yes, it only happens on Windows to me :-P

Still the same after changing ''' for ', though.

**Comment by javierfernandes** [comment] 2016-07-17 13:07
Ok, maybe writting it in a single line with explicit \n\r
I'll check, but as I don't have windows, it would be great if you could
also check that.

(I wonder if we can configure travis to run tests both in linux and windows)

**Comment by fdodino** [comment] 2016-07-17 13:50
Ok, this fixes the problem in Windows:

``` java
	@Test
	def void nativeMethodCallsWollokClosureThrowingASimpleException() {
		val newLine = "\n" //System.getProperty("line.separator")
		
		#["natives"->'''
class Repeater {
	method ntimes(n, closure) native
}

program natives {
	const repeater = new Repeater()

	const closure = { throw new Exception("SoundGarden") }
	try {
		repeater.ntimes(1, closure)
	}
	catch e {
		assert.equals(
"wollok.lang.Exception: SoundGarden''' + newLine +
	"\tat  [natives.wpgm]" + newLine +
	"\tat natives.Repeater.ntimes(n,closure) [natives.wpgm]" + newLine +
	"\tat  [natives.wpgm]" + newLine +
	"\",e.getStackTraceAsString())" + 
	'''
	} 
}
		''']
		.interpretPropagatingErrors
	}
```	

But, I think problem may be in printer object, because it's using \n instead of System.getProperty("line.separator").

**Comment by fdodino** [comment] 2016-07-17 13:55
Right

```java
class StringPrinter {
	var buffer = ""
	method println(obj) {
		buffer += obj.toString() + "\n"
	}
	method getBuffer() = buffer
}	
```

I'd like to use lineSeparator as a constant, in Wollok, to simplify testing situation like before. 
Don't know what is the best choice.
And also :+1:  to tell Travis to test in Linux and Windows platform.

**Comment by npasserini** [comment] 2016-07-17 21:47
Sounds good.

**Comment by fdodino** [comment] 2016-07-18 15:29
@matifreyre could you open a new issue? So I can fix it in another branch.

**Comment by javierfernandes** [comment] 2016-07-18 15:34
I never saw this issue before in many years developing java :(
I thought that \n was later translated by the VM into the platform specific.

This sucks.

PS:

"Java 7 now has a System.lineSeparator()
<http://docs.oracle.com/javase/8/docs/api/java/lang/System.html#lineSeparator-->
 method."

**Comment by matifreyre** [comment] 2016-07-18 15:53
> @matifreyre could you open a new issue? So I can fix it in another branch.

Done!

**Comment by fdodino** [comment] 2016-08-22 20:11
I hacked stackTrace in WollokRepl class

**Comment by npasserini** [comment] 2016-08-23 08:06
Please leave an open issue so that we eventually review this and fix the
repl so this hack is not more needed.

**Comment by fdodino** [comment] 2016-08-23 12:50
:+1:

**Comment by fdodino** [comment] 2016-08-31 11:07
Merged REPL-fixes branch

**Closed by fdodino** 2016-08-31 11:07 UTC
Labels: severity: 1 - Minor, type: Enhancement
