### ISSUE TITLE
Cannot self call method from Mixin

### ISSUE THREAD

**Issue by nrainhart** [uqbar-project/wollok#1019] opened 2016-10-13 15:26 UTC
Example:

```
mixin M1{
    method uno(){
        return 1
    } 
}

class C1 mixed with M1{
    method dos() = 1 + self.uno() 
}
```

It marks `method dos() = 1 + self.uno()` with "Non existant method or incorrect argument number"

And when you try to run it, it says the same in the console

**Comment by javierfernandes** [comment] 2016-10-13 20:14
Right. 
I was able to reproduce it even in "dev" (1.6).

I suspect that it is only an bug on the static checks which validates that methods on self exists. It is probably not taking into account inherited methods from mixins.
Which is weird since now all checks should use the "linearized" hierarchy.

Will work on it soon.

**Comment by javierfernandes** [comment] 2016-10-13 23:02
This is already fixed in "dev". Meaning that it will be part of wollok 1.6

We could consider also fixing it in 1.5.x if it is really necessary

**Closed** 2017-07-12 13:08 UTC
Labels: bug, component: mixins, component: validator, in progress
