### ISSUE TITLE
Run REPL without an associated file.

### ISSUE THREAD

**Issue by tesonep** [uqbar-project/wollok#3] opened 2015-03-12 18:41 UTC

**Comment by npasserini** [comment] 2015-03-14 19:58
Duplicates issue #10

**Comment by javierfernandes** [comment] 2015-12-29 12:27
Hey, shouldn't this be reopened ?
They are both marked as duplicates of each others #3 and #10 but none of them have associated commits. I think none of them have been solved

**Comment by npasserini** [comment] 2015-12-31 05:25
Done.

**Closed** 2016-05-09 15:37 UTC
Labels: duplicate

**Comment by flbulgarelli** [comment] 2016-05-09 16:15
Duplicate of #465

**Comment by flbulgarelli** [comment] 2016-05-09 16:16
Anyway, was this issue solved?

**Comment by tesonep** [comment] 2016-05-09 18:17
Yes, it is in the branch of development for 1.5
