### ISSUE TITLE
Writing arithmetic expressions in REPL has a weird behaviour

### ISSUE THREAD

**Issue by matifreyre** [uqbar-project/wollok#1033] opened 2016-10-29 11:44 UTC
Writing this:

```
> 1 + 2
```

And pressing enter right there, without anything else, doesn't evaluate the expression. Instead, it just adds a NL/CR and you can continue writing. If you press enter, another NL/CR is added. If you add a space and then press enter, the expression gets evaluated.

Now, if you press the up arrow to recall the last expression and delete all the extra NL/CR and leave only the original expression `> 1 + 2` with no space at the end, it does get evaluated.

After that last case where you get the expression evaluated, deleting the last `2` and writing it again doesn't change the behaviour, it keeps getting evaluated, but deleting `+ 2` and writing it again causes the same problem, so my belief is that this problem is somehow related with writing arithmetical operations. Instead, I don't have any problems with expressions like `1..5`, so I believe it's not related with operators in general, just arithmetic.

**Comment by fdodino** [comment] 2016-11-15 09:47
@matifreyre I could not reproduce it in Linux. I think it could be again a difference between NL and NL / CR in Linux and Windows.

**Comment by fdodino** [comment] 2017-04-21 14:36
@matifreyre does it happen to you in dev branch? Still not happening to me...

**Comment by tesonep** [comment] 2017-04-21 15:26
I could reproduced it in OSX, I think it has to do with the parser. The secret is not having nothing between the last '1' and the enter. It is like it is waiting for something more.

**Comment by tesonep** [comment] 2017-04-21 15:29
In OSX the problem is when you use the enter in the numpad. If you use the normal enter it is working, can you check the same???

**Comment by tesonep** [comment] 2017-04-21 15:29
@matifreyre @fdodino @npasserini

**Comment by matifreyre** [comment] 2017-04-21 15:44
OK... I'll have a look at it tonight, I don't have the environment
available right now.

**Comment by tesonep** [comment] 2017-04-21 15:48
@matifreyre I have fixed with the help of Polito, because he is the master of keycode events in Pharo.

**Closed** 2017-04-21 15:48 UTC
Labels: component: repl, type: bug
