### ISSUE TITLE
Error while editing a wollok program

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1222] opened 2017-08-19 21:16 UTC
This happened several times while editing a very simple program. I have to work in defining exact reproduction steps.

java.lang.NullPointerException
    at org.uqbar.project.wollok.ui.editor.hyperlinking.WollokEObjectAtOffsetHelper.findCrossReferenceNode(WollokEObjectAtOffsetHelper.java:49)
    at org.eclipse.xtext.resource.EObjectAtOffsetHelper.getCrossReferenceNode(EObjectAtOffsetHelper.java:64)
    at org.eclipse.xtext.resource.EObjectAtOffsetHelper.resolveCrossReferencedElementAt(EObjectAtOffsetHelper.java:51)
    at org.eclipse.xtext.resource.EObjectAtOffsetHelper.internalResolveElementAt(EObjectAtOffsetHelper.java:117)
    at org.eclipse.xtext.resource.EObjectAtOffsetHelper.resolveElementAt(EObjectAtOffsetHelper.java:35)
    at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer$1.exec(DefaultOccurrenceComputer.java:108)
    at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer$1.exec(DefaultOccurrenceComputer.java:1)
    at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:26)
    at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
    at org.eclipse.xtext.ui.editor.occurrences.DefaultOccurrenceComputer.createAnnotationMap(DefaultOccurrenceComputer.java:102)
    at org.eclipse.xtext.ui.editor.occurrences.OccurrenceMarker$MarkOccurrenceJob.run(OccurrenceMarker.java:123)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by fdodino** [comment] 2017-08-23 15:48
Hi @npasserini , I could reproduce it.

1) Add a new file. Name it pepita.wlk
2) Define a wko. Name it pepita.
3) Add a test, program or wlk file. It doesn't matter whether it is one or another.
Add following import:

import pepita.pepita

Import is crashing with a NPE.

```
Caused by: org.uqbar.project.wollok.interpreter.WollokRuntimeException: Error while resolving import 'pepita.pepita'
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.toResource(WollokGlobalScopeProvider.java:193)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.lambda$4(WollokGlobalScopeProvider.java:140)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:646)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.exists(IteratorExtensions.java:256)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.exists(IterableExtensions.java:222)
	at org.uqbar.project.wollok.scoping.WollokScopeExtensions.containsImport(WollokScopeExtensions.java:27)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.lambda$1(WollokImportedNamespaceAwareLocalScopeProvider.java:115)
	at org.eclipse.xtext.xbase.lib.internal.BooleanFunctionDelegate.apply(BooleanFunctionDelegate.java:41)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.doGetImportedNamespaceResolvers(WollokImportedNamespaceAwareLocalScopeProvider.java:123)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getImportedNamespaceResolvers(WollokImportedNamespaceAwareLocalScopeProvider.java:96)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getResourceScope(WollokImportedNamespaceAwareLocalScopeProvider.java:69)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:60)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:58)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:58)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:58)
	at org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.delegateGetScope(AbstractDeclarativeScopeProvider.java:72)
	at org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.getScope(AbstractDeclarativeScopeProvider.java:104)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getScope(DefaultLinkingService.java:59)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getLinkedObjects(DefaultLinkingService.java:120)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:247)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:222)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.uqbar.project.wollok.scoping.root.WollokRootLocator.calculateLevelsToRoot(WollokRootLocator.java:65)
	at org.uqbar.project.wollok.scoping.root.WollokRootLocator.levelsToRoot(WollokRootLocator.java:19)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.generateUri(WollokGlobalScopeProvider.java:207)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.toResource(WollokGlobalScopeProvider.java:183)
	... 55 more
```

Sometimes if you write

import pepita.*

also fires a NPE, but it is not easy to reproduce.

```
org.eclipse.emf.common.util.WrappedException: org.uqbar.project.wollok.interpreter.WollokRuntimeException: Error while resolving import 'pepita.*'
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:230)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doResolveLazyCrossReference(LazyLinkingResource.java:189)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.resolveLazyCrossReference(LazyLinkingResource.java:148)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.resolveLazyCrossReferences(LazyLinkingResource.java:134)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:498)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescription.computeReferenceDescriptions(DefaultResourceDescription.java:135)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescription$2.get(DefaultResourceDescription.java:123)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescription$2.get(DefaultResourceDescription.java:120)
	at org.eclipse.xtext.util.OnChangeEvictingCache.get(OnChangeEvictingCache.java:77)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescription.getReferenceDescriptions(DefaultResourceDescription.java:120)
	at org.eclipse.xtext.resource.DescriptionUtils.collectOutgoingReferences(DescriptionUtils.java:29)
	at org.eclipse.xtext.resource.impl.DefaultResourceDescriptionManager.isAffected(DefaultResourceDescriptionManager.java:117)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport.isReparseRequired(DirtyStateEditorSupport.java:649)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$UpdateEditorStateJob$1.exec(DirtyStateEditorSupport.java:161)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$UpdateEditorStateJob$1.exec(DirtyStateEditorSupport.java:1)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
	at org.eclipse.xtext.ui.editor.DirtyStateEditorSupport$UpdateEditorStateJob.run(DirtyStateEditorSupport.java:146)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.uqbar.project.wollok.interpreter.WollokRuntimeException: Error while resolving import 'pepita.*'
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.toResource(WollokGlobalScopeProvider.java:193)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.lambda$4(WollokGlobalScopeProvider.java:140)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:646)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.exists(IteratorExtensions.java:256)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.exists(IterableExtensions.java:222)
	at org.uqbar.project.wollok.scoping.WollokScopeExtensions.containsImport(WollokScopeExtensions.java:27)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.lambda$1(WollokImportedNamespaceAwareLocalScopeProvider.java:115)
	at org.eclipse.xtext.xbase.lib.internal.BooleanFunctionDelegate.apply(BooleanFunctionDelegate.java:41)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.doGetImportedNamespaceResolvers(WollokImportedNamespaceAwareLocalScopeProvider.java:123)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getImportedNamespaceResolvers(WollokImportedNamespaceAwareLocalScopeProvider.java:96)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getResourceScope(WollokImportedNamespaceAwareLocalScopeProvider.java:69)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:60)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:58)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:58)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:58)
	at org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.delegateGetScope(AbstractDeclarativeScopeProvider.java:72)
	at org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.getScope(AbstractDeclarativeScopeProvider.java:104)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getScope(DefaultLinkingService.java:59)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getLinkedObjects(DefaultLinkingService.java:120)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:247)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:222)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.uqbar.project.wollok.scoping.root.WollokRootLocator.calculateLevelsToRoot(WollokRootLocator.java:65)
	at org.uqbar.project.wollok.scoping.root.WollokRootLocator.levelsToRoot(WollokRootLocator.java:19)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.generateUri(WollokGlobalScopeProvider.java:207)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.toResource(WollokGlobalScopeProvider.java:183)
	... 55 more
```

**Comment by fdodino** [comment] 2017-08-23 18:18
Well, now I can not reproduce it...

**Comment by npasserini** [comment] 2017-08-23 21:22
It does not look like the same error to me.

**Comment by fdodino** [comment] 2017-08-23 23:53
Ok, deleting all and opening a new issue.

**Comment by fdodino** [comment] 2018-08-04 18:05
Since we could not reproduce this behavior, after a year, I think it is time to close the issue.
:smile:

**Closed by fdodino** 2018-08-04 18:05 UTC
Labels: component: import & scope system
